version: 2.1

jobs:
  hello:
    machine: true
    steps:  
      - run: echo 'Hello, world'
      - run: echo 'message from soo' > "message.txt"
      - run: msg=$(<message.txt)
      - run: echo "$msg"
      - run: echo "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"$msg\"}' ${SLACK_API_URL}"
workflows:
  welcome:
    jobs:
      - hello
