version: 2.1

jobs:
  hello:
    machine: true
    steps:
      - checkout
      - run: echo 'Hello, world'
      - run: cat .circleci/config.yml
      - run: cat message.txt    

workflows:
  welcome:
    jobs:
      - hello
